services:
  postgres:
    image: 'bitnami/postgresql:15'
    restart: always
    networks:
      - app-tier
    ports:
      - "5433:5432"
    volumes:
      - "postgres_data:/bitnami/postgresql"
    environment:
      - POSTGRESQL_USERNAME=devuser
      - POSTGRESQL_PASSWORD=example
      - POSTGRESQL_DATABASE=devuser
  excel-database-loader-api:
    image: halversondm/excel-database-loader-api:latest
    networks:
      - app-tier
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/devuser
    depends_on:
      - postgres
  excel-database-loader-ui:
    image: halversondm/excel-database-loader-ui:latest
    networks:
      - app-tier
    ports:
      - "9200:8080"
    depends_on:
      - postgres
      - excel-database-loader-api
networks:
  app-tier:
    driver: bridge
volumes:
  postgres_data:
    driver: local