--liquibase formatted sql

--changeset halversondm:adding-table
CREATE TABLE HOMEOWNER
(
    LOT_NUMBER  INTEGER PRIMARY KEY,
    CLOSE_DATE  VARCHAR(20),
    FIRST_NAME  VARCHAR(50),
    SECOND_NAME VARCHAR(50),
    LAST_NAME   VARCHAR(50),
    ADDRESS     VARCHAR(100),
    ALTERNATE_ADDRESS VARCHAR(100),
    CITY        VARCHAR(50),
    STATE       VARCHAR(50),
    ZIP         VARCHAR(20),
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
--rollback DELETE TABLE ACCOUNT;

--changeset halversondm:adding-index
CREATE INDEX IDX_HOMEONWER_NAME ON HOMEOWNER USING gin(to_tsvector('english', LAST_NAME));
CREATE INDEX IDX_HOMEONWER_ADDRESS ON HOMEOWNER USING gin(to_tsvector('english', ADDRESS));
--rollback DROP INDEX IDX_HOMEONWER_NAME;
--rollback DROP INDEX IDX_HOMEONWER_ADDRESS;

--changeset halversondm:updating-close-date-length
ALTER TABLE HOMEOWNER
    ALTER COLUMN CLOSE_DATE TYPE VARCHAR(100);
--rollback ALTER TABLE HOMEOWNER ALTER COLUMN CLOSE_DATE TYPE VARCHAR(20);