name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '22'
      - name: Build with Maven
        run: mvn -e --batch-mode clean install
      - name: Build Docker images for all Dockerfiles
        run: |
          find . -name 'Dockerfile' | while read dockerfile; do
            dir=$(dirname "$dockerfile")
            imagename=$(basename "$dir")
            docker build -t "${imagename}:latest" "$dir"
          done